import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  /**
   * The font on the Figma design system is `Poppins`, so I'm using that.
   */
  variable: "--font-poppins",
  /**
   * Normal = 400.
   * Bold = 700.
   * Based on the Figma design system, most of the text is `400` (normal),  and the ones with bolds are `600` (semi bold) and `700` (bold), so i'm loading only those three.
   * If in future, we need to load more weights, we can do it by adding them to the array.
   */
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
        <Toaster position="top-left" />
      </body>
    </html>
  );
}
